### ISSUE TITLE
GUI/Layout Change?

### ISSUE THREAD

**Issue by spxctreofficial** [misode/misode.github.io#121]
So recently I found that the GUI and layout were changed for the generator. Was this intentional or accidental? As the new layout makes it somewhat hard to look at and kind of more complicated.

Other than that, nice generator!

**Comment by misode** [comment]
@realspectr3x Hi! Thanks a lot for the feedback. The layout has indeed changed, and this was intentional. There were some changes behind the scenes and this required a whole require and restyle. That said I do want to improve the style. I have pushed some I'd be very thankful if you could take a look and provide tell me what you think.
![image](https://user-images.githubusercontent.com/17352009/95028558-38f4ca00-06a1-11eb-859b-acfd0e977c51.png)

**Comment by realspectr3x** [comment]
Yes I will take a look at it and I'll give you back some ideas in a bit

**Comment by realspectr3x** [comment]
I do like the changes, but what imo I think the GUI would look even better with some eye-candy effects, animations, and maybe a font change. Just my suggestions and opinions!

**Comment by misode** [comment]
If there is a specific UI change, please make a new issue.
