### ISSUE TITLE
General Question: How are you adding new Translations?

### ISSUE THREAD

**Issue by catter1** [misode/misode.github.io#296]
On the localization site, to request a new translation, it says to create an issue here. I am trying to set up Weblate for my own thing, and am curious on how you are doing it on the backend, since the Weblate documentation is not super clear. When you see a translation request, how do you add it into the system? I appreciate any info you reply with.

**Comment by SPGoding** [comment]
There is a "Start new translation" button on the component page for admins to add new languages. You could also create a new language file manually (for example, under `src/locales` for this repo) and it will get picked up by Weblate automatically.

You could also change the "Adding new translation" option in the component settings (Manage -> Settings -> Files) to "Create new lang file" so that all users can add new translations without having to ask the maintainers.

**Comment by catter1** [comment]
Awesome, thanks for the info!
