### ISSUE TITLE
Support for new advancement format

### ISSUE THREAD

**Issue by SPGoding** [misode/misode.github.io#80]

**Comment by misode** [comment]
I've had some thought about this one. The hardest part is figuring out the UI, since both formats need to be supported at the same time.

I'm considering this. Where clicking on either of the two options acts as a collapse. Unsure if "predicate" and "conditions" are the right words though. The new format should be plural though.
![image](https://user-images.githubusercontent.com/17352009/80928581-abd1e000-8da5-11ea-99a2-372adfb2a9b6.png)

**Comment by SPGoding** [comment]
Sweet! `Legacy` might be less consusing than `Predicate`.

**Comment by misode** [comment]
That's not a bad idea, since the article explicitly mentioned they're deprecated now.

**Comment by misode** [comment]
This has been added in the dev version: https://misode.github.io/dev/advancement/
